name: Telegram Bot 24/7

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'ni yuklash
        uses: actions/checkout@v3

      - name: Python o'rnatish
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Kutubxonalarni o'rnatish
        run: pip install -r requirements.txt

      - name: Botni ishga tushirish
        run: python main.py
